version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - Androz2091
  ignore:
  - dependency-name: i18next
    versions:
    - 20.1.0
    - 20.2.0
  - dependency-name: "@sentry/node"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.5
  - dependency-name: "@discordjs/opus"
    versions:
    - 0.5.0
